title: Team Kainashi

markdown: kramdown

kramdown:
  math_engine: mathjax

include:
  - index.md
  - pppiii2.md

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
